### ISSUE TITLE
Support Flutter 3.38

### ISSUE THREAD

**Issue by teganscott** [Navigine/Indoor-Navigation-Flutter-SDK-2.0#10]
**Describe the bug**
Support Flutter 3.38

**To Reproduce**
1. Get the 3.38 stable release of Flutter (or newer)
2. Run the example app on Android (it appears to still be working on iOS)
3. See gradle and lifecycle issues

Such as: 
```
throw new GradleException("You are applying Flutter's main Gradle plugin imperatively using \
the apply script method, which is not possible anymore. \
Migrate to applying Gradle plugins with the declarative plugins block: \
https://flutter.dev/to/flutter-gradle-plugin-apply\n\
")
```

**Comment by PavelTychinin** [comment]
Hi, Tegan. Thanks for the issue. It should be fixed now. Can you check?

**Comment by teganscott** [comment]
Hi Pavel, 

I updated the project to read from the git repository, and am unfortunately still getting Android errors. 

` Failed to lookup symbol 'library_dart_is_init': undefined symbol: library_dart_is_init`

This is where it is failing:
```
Future<void> initNavigineSdk() async {
  if (_libraryDartDlIsInit()) return; // FAILS HERE

  _libraryDartDlInit(NativeApi.initializeApiDLData);
  await SdkMethodChannel('navigine_sdk').invokeMethod('init');
}
```

**Comment by teganscott** [comment]
@PavelTychinin please notify when this will be updated. We are unable to offer these services to our clients until it is available. Thanks

**Comment by PavelTychinin** [comment]
Hi @teganscott. We are planning to release fix next week

**Comment by PavelTychinin** [comment]
@teganscott can you try latest version ?

**Comment by teganscott** [comment]
Our developer posted in another thread about continuing issues. Thanks!
https://github.com/Navigine/Indoor-Navigation-Flutter-SDK-2.0/issues/12

**Comment by PavelTychinin** [comment]
@teganscott Release will be done tomorrow

**Comment by PavelTychinin** [comment]
@teganscott done
